import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

// Import Roboto font
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // You can include other weights if needed
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
